/**************************************************************************
 *   This file is part of PYQINT-GUI.                                     *
 *                                                                        *
 *   Author: Ivo Filot <ivo@ivofilot.nl>                                  *
 *                                                                        *
 *   PYQINT-GUI is free software:                                         *
 *   you can redistribute it and/or modify it under the terms of the      *
 *   GNU General Public License as published by the Free Software         *
 *   Foundation, either version 3 of the License, or (at your option)     *
 *   any later version.                                                   *
 *                                                                        *
 *   PYQINT-GUI is distributed in the hope that it will be useful,        *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty          *
 *   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.              *
 *   See the GNU General Public License for more details.                 *
 *                                                                        *
 *   You should have received a copy of the GNU General Public License    *
 *   along with this program.  If not, see http://www.gnu.org/licenses/.  *
 *                                                                        *
 **************************************************************************/

#include "job_script_writer.h"

#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QTextStream>

#include "config.h"

QString JobScriptWriter::python_string(const QString& str) {
    QString result = "'";
    for(const QChar ch : str) {
        switch(ch.unicode()) {
            case '\\': result += "\\\\"; break;
            case '\'': result += "\\'"; break;
            case '\n': result += "\\n"; break;
            case '\r': result += "\\r"; break;
            case '\t': result += "\\t"; break;
            default:
                if(ch.unicode() < 0x20) {
                    result += QString("\\x%1").arg((int)ch.unicode(), 2, 16, QChar('0'));
                } else {
                    result += ch;
                }
        }
    }
    result += "'";
    return result;
}

QString JobScriptWriter::python_float(double v) {
    // repr-like formatting that round-trips and is always a float literal
    QString s = QString::number(v, 'g', 17);
    if(!s.contains('.') && !s.contains('e') && !s.contains("inf") && !s.contains("nan")) {
        s += ".0";
    }
    return s;
}

QString JobScriptWriter::generate(const JobSpec& spec) {
    const bool restricted = spec.method == HFMethod::Restricted;
    const bool geomopt = spec.type == JobType::GeometryOptimization;
    const QString basis = python_string(spec.basis);

    QString src;
    QTextStream out(&src);

    // ------------------------------------------------------------------
    // header
    // ------------------------------------------------------------------
    out << "#!/usr/bin/env python3\n"
        << "# -*- coding: utf-8 -*-\n"
        << "#\n"
        << "# Job script generated by " << PROGRAM_NAME << " " << PROGRAM_VERSION
        << " on " << QDateTime::currentDateTime().toString("yyyy-MM-dd HH:mm:ss") << "\n"
        << "#\n"
        << "# Calculation  : " << spec.description() << "\n"
        << "# Molecule     : " << spec.molecule.get_name().simplified() << " (" << spec.molecule.formula() << ")\n"
        << "# Charge       : " << spec.charge << "\n"
        << "# Multiplicity : " << spec.multiplicity << "\n"
        << "#\n"
        << "# This script only uses the public PyQInt API and can be run on its own:\n"
        << "#\n"
        << "#     python job.py\n"
        << "#\n"
        << "# The helper module pyqint_gui_export.py (next to this script) writes all\n"
        << "# results to " << RESULT_FILENAME << ", which can be opened in " << PROGRAM_NAME << ".\n"
        << "#\n\n";

    // ------------------------------------------------------------------
    // imports
    // ------------------------------------------------------------------
    QStringList imports = {"Molecule"};
    if(geomopt) {
        imports << "GeometryOptimization";
    } else {
        imports << "HF";
    }
    if(spec.foster_boys) {
        imports << "FosterBoys";
    }

    out << "import time\n\n"
        << "from pyqint import " << imports.join(", ") << "\n"
        << "from pyqint_gui_export import export_result, progress\n\n";

    // ------------------------------------------------------------------
    // job settings, echoed into the result file
    // ------------------------------------------------------------------
    out << "JOB = {\n"
        << "    'type': " << python_string(geomopt ? "geometry_optimization" : "single_point") << ",\n"
        << "    'method': " << python_string(restricted ? "rhf" : "uhf") << ",\n"
        << "    'basis': " << basis << ",\n"
        << "    'charge': " << spec.charge << ",\n"
        << "    'multiplicity': " << spec.multiplicity << ",\n"
        << "    'itermax': " << spec.itermax << ",\n"
        << "    'tolerance': " << python_float(spec.tolerance) << ",\n"
        << "    'use_diis': " << (spec.use_diis ? "True" : "False") << ",\n"
        << "    'ortho': " << python_string(spec.ortho) << ",\n";
    if(geomopt) {
        out << "    'gtol': " << python_float(spec.gtol) << ",\n";
    }
    out << "    'foster_boys': " << (spec.foster_boys ? "True" : "False") << ",\n"
        << "}\n\n";

    // ------------------------------------------------------------------
    // molecule
    // ------------------------------------------------------------------
    out << "# --- molecule (coordinates in angstrom; PyQInt converts to bohr) ---\n"
        << "mol = Molecule(" << python_string(spec.molecule.get_name().simplified()) << ")\n";
    for(const auto& atom : spec.molecule.get_atoms()) {
        out << QString("mol.add_atom(%1, %2, %3, %4, unit='angstrom')\n")
               .arg(python_string(atom.element), 4)
               .arg(atom.position.x, 14, 'f', 8)
               .arg(atom.position.y, 14, 'f', 8)
               .arg(atom.position.z, 14, 'f', 8);
    }
    out << "mol.set_charge(" << spec.charge << ")\n\n";

    out << "start = time.time()\n\n";

    // ------------------------------------------------------------------
    // calculation
    // ------------------------------------------------------------------
    if(geomopt) {
        out << "# --- geometry optimization (restricted Hartree-Fock) ---\n"
            << "progress('optimization')\n"
            << "opt = GeometryOptimization(mol, " << basis << ", verbose=True).run(gtol=JOB['gtol'])\n"
            << "res = opt['data']    # Hartree-Fock result of the final geometry\n\n";
    } else {
        out << "# --- Hartree-Fock calculation ---\n"
            << "progress('scf')\n";
        if(restricted) {
            out << "res = HF(mol, " << basis << ").rhf(\n";
        } else {
            out << "res = HF(mol, " << basis << ").uhf(\n"
                << "    multiplicity=JOB['multiplicity'],\n";
        }
        out << "    itermax=JOB['itermax'],\n"
            << "    use_diis=JOB['use_diis'],\n"
            << "    tolerance=JOB['tolerance'],\n"
            << "    ortho=JOB['ortho'],\n"
            << "    verbose=True,\n"
            << ")\n\n";
    }

    if(spec.foster_boys) {
        out << "# --- Foster-Boys localization of the occupied orbitals ---\n"
            << "progress('localization')\n"
            << "fb = FosterBoys(res, seed=" << spec.fb_seed << ").run(nr_runners=" << spec.fb_runners << ")\n\n";
    }

    // ------------------------------------------------------------------
    // export
    // ------------------------------------------------------------------
    out << "# --- store all results ---\n"
        << "export_result(\n"
        << "    " << python_string(RESULT_FILENAME) << ",\n"
        << "    job=JOB,\n"
        << "    mol=mol,\n"
        << "    hf=res,\n";
    if(spec.foster_boys) {
        out << "    fosterboys=fb,\n";
    }
    if(geomopt) {
        out << "    geomopt=opt,\n";
    }
    out << "    walltime=time.time() - start,\n"
        << ")\n";

    return src;
}

QString JobScriptWriter::write_job_directory(const JobSpec& spec, const QString& directory) {
    QDir dir(directory);
    if(!dir.exists() && !QDir().mkpath(directory)) {
        return QString("Cannot create job directory %1").arg(directory);
    }

    // job script
    QFile script(dir.filePath(SCRIPT_FILENAME));
    if(!script.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return QString("Cannot write %1").arg(script.fileName());
    }
    script.write(generate(spec).toUtf8());
    script.close();

    // geometry, for convenience
    QFile xyz(dir.filePath("molecule.xyz"));
    if(xyz.open(QIODevice::WriteOnly | QIODevice::Text)) {
        xyz.write(spec.molecule.to_xyz().toUtf8());
        xyz.close();
    }

    // helper module
    QFile helper_src(HELPER_RESOURCE);
    if(!helper_src.open(QIODevice::ReadOnly)) {
        return QString("Cannot read embedded resource %1").arg(HELPER_RESOURCE);
    }
    QFile helper_dst(dir.filePath(HELPER_FILENAME));
    if(!helper_dst.open(QIODevice::WriteOnly)) {
        return QString("Cannot write %1").arg(helper_dst.fileName());
    }
    helper_dst.write(helper_src.readAll());

    return QString();
}
