# -*- coding: utf-8 -*-
"""
Helper module used by the job scripts generated by PyQInt-GUI.

The generated ``job.py`` scripts perform the actual calculation using the
public PyQInt API; this module only takes care of two things:

  * reporting progress to the GUI (lines starting with ``@@PYQINT-GUI``)
  * writing all results to a single, self-describing JSON file

You can safely run a generated job script outside of the GUI; the JSON file
it produces can be re-opened in PyQInt-GUI via File -> Open result.
"""

import json
import platform
import sys
import time

import numpy as np
import pyqint

SCHEMA_VERSION = 1
PROGRESS_TAG = "@@PYQINT-GUI"

_SHELL_LABELS = "spdfghi"


def progress(stage, **kwargs):
    """
    Report progress to the GUI; harmless when run from the command line.
    """
    msg = {"stage": stage}
    msg.update(kwargs)
    print("%s %s" % (PROGRESS_TAG, json.dumps(msg)), flush=True)


# ---------------------------------------------------------------------------
# conversion helpers
# ---------------------------------------------------------------------------
def _mat(m):
    if m is None:
        return None
    return np.asarray(m, dtype=np.float64).tolist()


def _scalar(v):
    if v is None:
        return None
    return float(v)


def _molecule_to_dict(mol, nuclei):
    atoms = []
    for (symbol, _), (pos, charge) in zip(mol.get_atoms(), nuclei):
        atoms.append({
            "element": symbol,
            "atomic_number": int(charge),
            "position": [float(x) for x in pos],   # bohr
        })

    return {
        "name": mol.get_name(),
        "charge": int(mol.get_charge()),
        "units": "bohr",
        "atoms": atoms,
    }


def _atom_index(p, nuclei):
    for i, (pos, _) in enumerate(nuclei):
        if np.linalg.norm(np.asarray(p) - np.asarray(pos)) < 1e-3:
            return i
    return -1


def _basis_to_list(cgfs, nuclei, mol):
    """
    Export the contracted Gaussian functions. The GUI uses these to evaluate
    molecular orbitals on a grid. Each primitive is stored as
    [c, alpha, l, m, n], where c is the contraction coefficient *excluding*
    the normalization constant of the primitive (identical to PyQInt).
    """
    symbols = [a[0] for a in mol.get_atoms()]
    result = []
    for cgf in cgfs:
        gtos = [[float(g.c), float(g.alpha), int(g.l), int(g.m), int(g.n)]
                for g in cgf.gtos]
        l, m, n = gtos[0][2:5] if gtos else (0, 0, 0)
        lsum = l + m + n
        suffix = "x" * l + "y" * m + "z" * n
        aidx = _atom_index(cgf.p, nuclei)
        el = symbols[aidx] if aidx >= 0 else "?"
        result.append({
            "center": [float(x) for x in cgf.p],   # bohr
            "atom": aidx,
            "label": "%s%i %s%s" % (el, aidx + 1, _SHELL_LABELS[lsum], suffix),
            "gtos": gtos,
        })
    return result


def _orbital_set(label, spin, energies, coefficients, occupations):
    """
    Coefficients are stored per molecular orbital, i.e. entry i is the
    list of basis-function coefficients of the i-th orbital (column i of
    the PyQInt coefficient matrix).
    """
    C = np.asarray(coefficients, dtype=np.float64)
    return {
        "label": label,
        "spin": spin,
        "energies": [float(e) for e in energies],
        "occupations": [float(o) for o in occupations],
        "coefficients": C.T.tolist(),
    }


def _populations(nuclei, cgfs, P, S):
    """
    Mulliken and Löwdin atomic charges. Uses the same expressions as
    pyqint.PopulationAnalysis but also works for UHF (total density).
    """
    PS = P @ S
    s, U = np.linalg.eigh(S)
    Shalf = U @ np.diag(np.sqrt(s)) @ U.T
    PL = Shalf @ P @ Shalf

    idx = [_atom_index(c.p, nuclei) for c in cgfs]
    mulliken, lowdin = [], []
    for a, (_, charge) in enumerate(nuclei):
        mu = [i for i, j in enumerate(idx) if j == a]
        mulliken.append(float(charge - sum(PS[i, i] for i in mu)))
        lowdin.append(float(charge - sum(PL[i, i] for i in mu)))
    return {"mulliken": mulliken, "lowdin": lowdin}


_ENERGY_KEYS = ["energy", "ekin", "enuc", "erep", "ex", "ecore", "ej",
                "ex_alpha", "ex_beta", "enucrep"]

_MATRIX_KEYS = {
    "overlap": "S (overlap)",
    "kinetic": "T (kinetic)",
    "nuclear": "V (nuclear attraction)",
    "hcore": "H (core Hamiltonian)",
    "fock": "F (Fock)",
    "fock_alpha": "Fα (Fock, alpha)",
    "fock_beta": "Fβ (Fock, beta)",
    "density": "P (density)",
    "density_alpha": "Pα (density, alpha)",
    "density_beta": "Pβ (density, beta)",
    "transform": "X (orthogonalization)",
}


def _hf_to_dict(hf):
    unrestricted = "orbe_alpha" in hf
    N = len(hf["cgfs"])

    scf = {
        "method": "uhf" if unrestricted else "rhf",
        "nelec": int(hf["nelec"]),
        "iterations": [float(e) for e in hf["energies"]],
        "components": {k: _scalar(hf[k]) for k in _ENERGY_KEYS if k in hf},
    }

    if unrestricted:
        na, nb = int(hf["nalpha"]), int(hf["nbeta"])
        scf.update({"nalpha": na, "nbeta": nb,
                    "multiplicity": int(hf["multiplicity"])})
        orbitals = [
            _orbital_set("Canonical (α)", "alpha", hf["orbe_alpha"],
                         hf["orbc_alpha"], [1 if i < na else 0 for i in range(N)]),
            _orbital_set("Canonical (β)", "beta", hf["orbe_beta"],
                         hf["orbc_beta"], [1 if i < nb else 0 for i in range(N)]),
        ]
    else:
        nocc = int(hf["nelec"]) // 2
        orbitals = [
            _orbital_set("Canonical", "restricted", hf["orbe"], hf["orbc"],
                         [2 if i < nocc else 0 for i in range(N)]),
        ]

    matrices = {}
    for key, label in _MATRIX_KEYS.items():
        if key in hf and hf[key] is not None:
            matrices[key] = {"label": label, "data": _mat(hf[key])}

    return scf, orbitals, matrices


# ---------------------------------------------------------------------------
# public API
# ---------------------------------------------------------------------------
def export_result(path, *, job, mol, hf, fosterboys=None, geomopt=None,
                  walltime=None):
    """
    Write all results of a calculation to a JSON file.

    Parameters
    ----------
    path : str
        Output filename.
    job : dict
        Job settings as set by the GUI (echoed back into the result file).
    mol : pyqint.Molecule
        The molecule (final geometry for optimizations).
    hf : dict
        Result dictionary of HF.rhf() or HF.uhf().
    fosterboys : dict, optional
        Result dictionary of FosterBoys.run().
    geomopt : dict, optional
        Result dictionary of GeometryOptimization.run().
    """
    progress("export")

    nuclei = hf["nuclei"]
    scf, orbitals, matrices = _hf_to_dict(hf)

    result = {
        "schema": SCHEMA_VERSION,
        "generator": {
            "pyqint_version": pyqint.__version__,
            "python_version": platform.python_version(),
            "platform": platform.platform(),
            "created": time.strftime("%Y-%m-%dT%H:%M:%S"),
        },
        "job": job,
        "molecule": _molecule_to_dict(mol, nuclei),
        "basis": _basis_to_list(hf["cgfs"], nuclei, mol),
        "scf": scf,
        "orbitals": orbitals,
        "matrices": matrices,
        "populations": _populations(nuclei, hf["cgfs"], hf["density"],
                                     hf["overlap"]),
        "timing": {k: _scalar(v) for k, v in hf["time_stats"].items()
                   if not isinstance(v, (list, tuple))},
    }

    if walltime is not None:
        result["timing"]["walltime"] = float(walltime)

    if fosterboys is not None:
        nocc = int(hf["nelec"]) // 2
        N = len(hf["cgfs"])
        fbset = _orbital_set("Foster-Boys", "restricted", fosterboys["orbe"],
                             fosterboys["orbc"],
                             [2 if i < nocc else 0 for i in range(N)])
        orbitals.append(fbset)
        result["localization"] = {
            "method": "foster-boys",
            "r2start": _scalar(fosterboys["r2start"]),
            "r2final": _scalar(fosterboys["r2final"]),
            "iterations": int(fosterboys["nriter"]),
        }

    if geomopt is not None:
        opt = geomopt["opt"]
        result["optimization"] = {
            "success": bool(opt.success),
            "message": str(opt.message),
            "energies": [float(e) for e in geomopt["energies"]],
            "frames": [_mat(c) for c in geomopt["coordinates"]],   # bohr
            "forces": [_mat(f) for f in geomopt["forces"]],
        }

    with open(path, "w", encoding="utf-8") as f:
        json.dump(result, f)

    progress("done", path=path)
    return result
